# Generated by Django 2.2.7 on 2019-12-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='学号')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='手机号')),
                ('college', models.CharField(max_length=20, null=True, verbose_name='学院')),
                ('class_num', models.CharField(max_length=20, null=True, verbose_name='班级号')),
            ],
            options={
                'verbose_name': '用户',
            },
        ),
    ]
