# Generated by Django 2.2.7 on 2019-12-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('stuId', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='用户名')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
