# Generated by Django 2.2.7 on 2019-12-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('stuId', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True, verbose_name='学号')),
                ('nickname', models.CharField(max_length=20, verbose_name='昵称')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('campus', models.CharField(blank=True, max_length=20, null=True, verbose_name='学院')),
                ('class_num', models.CharField(blank=True, max_length=20, null=True, verbose_name='班级号')),
                ('is_staff', models.BooleanField(blank=True, default=False)),
                ('is_superuser', models.BooleanField(blank=True, default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'abstract': False,
            },
        ),
    ]
