# Generated by Django 2.2.7 on 2019-12-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191208_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stuId',
            field=models.BigIntegerField(max_length=13, primary_key=True, serialize=False, unique=True, verbose_name='用户名'),
        ),
    ]
