# Generated by Django 2.2.7 on 2019-12-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191208_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='milestin', max_length=20, verbose_name='昵称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stuId',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, unique=True, verbose_name='学号'),
        ),
    ]
