# Generated by Django 2.2.7 on 2019-12-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191208_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='手机号'),
        ),
    ]
