# Generated by Django 2.2.7 on 2019-12-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campus',
            field=models.CharField(max_length=20, null=True, verbose_name='学院'),
        ),
    ]
