# Generated by Django 2.2.7 on 2019-12-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_num',
            field=models.CharField(max_length=20, null=True, verbose_name='班级号'),
        ),
    ]
