# Generated by Django 2.2.7 on 2019-12-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20191208_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='campus',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='user',
            name='class_num',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='班级号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_stu_authenticated',
            field=models.BooleanField(default=False, editable=False, verbose_name='是否认证'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
    ]
