# Generated by Django 2.2.7 on 2019-12-21 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('comId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='商品id')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('price', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='价格')),
                ('description', models.TextField(max_length=300, verbose_name='描述')),
                ('stuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='商品发布者')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ('comId',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='订单id')),
                ('status', models.IntegerField(choices=[(0, '已经被预定'), (1, '预定已同意'), (2, '预定不同意')], default=0, verbose_name='状态')),
                ('appointment_time', models.DateTimeField(auto_now=True, verbose_name='预约时间')),
                ('finished_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('comId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='com_order', to='order.Commodity', verbose_name='商品')),
                ('stuId_buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_orders', to=settings.AUTH_USER_MODEL, verbose_name='买家')),
                ('stuId_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_orders', to=settings.AUTH_USER_MODEL, verbose_name='卖家')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='CommodityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='类型')),
                ('comId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='order.Commodity', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品类型',
                'verbose_name_plural': '商品类型',
                'ordering': ('comId',),
                'unique_together': {('comId', 'type')},
            },
        ),
        migrations.CreateModel(
            name='CommodityPics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to=order.models.user_directory_path, verbose_name='图片')),
                ('comId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='order.Commodity', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'ordering': ('comId',),
                'unique_together': {('comId', 'pic')},
            },
        ),
    ]
