# Generated by Django 2.2.7 on 2019-12-11 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comId',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='com_order', to='order.Commodity', verbose_name='商品'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commodity',
            name='stuId',
            field=models.ForeignKey(default=2019, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='商品发布者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='stuId_seller',
            field=models.ForeignKey(default=2019, on_delete=django.db.models.deletion.CASCADE, related_name='seller_orders', to=settings.AUTH_USER_MODEL, verbose_name='卖家'),
            preserve_default=False,
        ),
    ]
